Add AddCommand, DeleteCommand, CommandResult, enum in Task
AY2021S1-CS2113T-T09-2/tp pull request #17
Opened 2020-10-03 18:06 UTC by Aseanseen

2020-10-03 18:58 UTC, f0fz requested changes
Looks fine overall, just one thing to change I think.

2020-10-03 18:58 UTC, f0fz commented on src/main/java/seedu/duke/command/CommandResult.java
> -    public String getFeedbackToUser() {
If removing getter function, then the `feedbackToUser` attribute should not be private.

2020-10-06 14:14 UTC, Aseanseen commented
Amended the AddCommand, DeleteCommand, enum in Parser. Checks are failing due to the functions it requires from other classes.

2020-10-06 14:20 UTC, f0fz approved these changes
Looks good, let's go

2020-10-06 14:32 UTC, tobiasceg commented
could u add, a AddCommand.FORMAT
a constant that outputs the correct format on how a addcommand will be read

2020-10-06 14:37 UTC, tobiasceg commented on src/main/java/seedu/duke/command/add/AddCommand.java
> +public class AddCommand extends Command {
Add a constant FORMAT

2020-10-06 14:37 UTC, Aseanseen commented
> could u add, a AddCommand.FORMAT
> a constant that outputs the correct format on how a addcommand will be read

Ok, added

2020-10-06 16:13 UTC, merged