Update DG
AY2021S1-CS2113T-T09-2/tp pull request #251
Opened 2020-11-07 06:57 UTC by amalinasani

* Add missing user stories 
* Add manual testing for list, help, and summary

2020-11-07 09:09 UTC, tobiasceg approved these changes

2020-11-07 11:43 UTC, Aseanseen requested changes
Some slight amends but generally ok

2020-11-07 11:43 UTC, Aseanseen commented on docs/DeveloperGuide.md
> +|v2.0|user|receive help messages and prompts|seamlessly navigate and use ra.VI's features|
Not too sure about this user story.\
Maybe something like receive help easily so that I know how to use ravi efficiently

2020-11-07 11:43 UTC, Aseanseen commented on docs/DeveloperGuide.md
> +    1. Test case: `list -t`, after adding the tasks "read book", "buy stuff" have been added in succession.\
Maybe instead of saying add, say that these tasks are in the task list, because it might be possible the task list is already in the json

2020-11-07 11:43 UTC, Aseanseen commented on docs/DeveloperGuide.md
> +    1. Test case: `list -m`, after adding the modules "CS2113T", and "CS2101" have been added in succession.\
Same comment as above

2020-11-07 11:43 UTC, Aseanseen commented on docs/DeveloperGuide.md
> +    2. Test case: `list -m` when no modules have been added.\
Same comment as above

2020-11-07 11:43 UTC, Aseanseen commented on docs/DeveloperGuide.md
> +    `summary` after inputting the following:
Rather than input, maybe say these tasks are in the task list, e.g. show what is in the task list

2020-11-08 10:32 UTC, Aseanseen approved these changes
Looks good to merge

2020-11-08 10:33 UTC, merged