Added Grade n Cap Command
AY2021S1-CS2113T-T09-2/tp pull request #85
Opened 2020-10-20 08:55 UTC by tobiasceg

Grade command: grade <mod> <mc> <grade>
grade ranges from A+ to F 
mod must exist in module list 

cap command is just cap 
cap will be calculated from module list

2020-10-20 11:10 UTC, Aseanseen requested changes
Suggesting some minimal edits

2020-10-20 11:10 UTC, Aseanseen commented on src/main/java/seedu/duke/command/cap/CapCommand.java
> +                    * gradeConvert(ModuleManager.getModulesMap().get(i).getModuleGrade());
Maybe set a variable to the set so that you do not have to keep repeating the getModulesMap()

2020-10-20 11:10 UTC, Aseanseen commented on src/main/java/seedu/duke/data/ModuleManager.java
> +            modulesMap.get(moduleCode.getModuleCode()).setModuleCredit(moduleCredit);
Maybe assign a value to moduleCode.getModuleCode() so that you do not keep calling it

2020-10-20 11:10 UTC, Aseanseen commented on src/main/java/seedu/duke/parser/GradeCommandParser.java
> +        }
I think I have seen this method appear multiple times in many parsers, could we extract it to a method?

2020-10-20 11:10 UTC, Aseanseen commented on src/main/java/seedu/duke/command/grade/GradeCommand.java
> +    protected void grade(Module moduleToBeGraded) throws InvalidGradeException, ModuleManager.ModuleNotFoundException {
Is there a reason why this is protected rather than private?

2020-10-25 12:25 UTC, f0fz approved these changes
Looks fine

2020-10-25 15:04 UTC, merged